### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by artifactdev** [FinndropStudios/GifRocket#17]
On my actual version of Rocket.Chat i can't get it to work. Filled the outgoing webhook the way it stands in the README but when I type !gif or !gif pizza nothing is happening.

**Comment by MonGMZ** [comment]
I tried to test it today and it didn't work either.

**Comment by manuelbachl** [comment]
Thats strange - on our side it works well. But maybe there was an update on RC last hours which broke this. We need to check. In the meantime, have a look if this issue may be the same: https://github.com/RocketChat/Rocket.Chat/issues/5896
Do other integrations work well?

**Comment by rabidang3ls** [comment]
I just tried to install this integration and am having the same issue as @artifactdev

**Comment by manuelbachl** [comment]
How about this? Is this still open?

**Comment by AlexanderPlaza** [comment]
Currently tried this on the current rocket.chat snappy package. It's working without any issues.

**Comment by AlexanderPlaza** [comment]
Does it just post a random gif related to what you type? Or is it possible to do some inline preview before sending?

**Comment by manuelbachl** [comment]
First, thanks for your status feedback.
But as far as I know, it is not possible to have a preview, because the webhook, which grabs the gif from giphy is just executed after sending, not while typing. To get previews working, Rocket.Chat would need to implement this feature. But I don't think they will do this, because it could raise traffic to an immense amount of requests (except they don't implement a timeout for sending the string you entered to giphy). But feel free to open a feature request on their side ;-)

**Comment by manuelbachl** [comment]
related to https://github.com/FinndropStudios/GifRocket/issues/18
